/*
 * defaultTitle
 *
 * defaultDescription
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CollectionMeta {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The size of the collection in bytes.
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    /// The status of the collection.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The dimension of the vectors in the collection.
    #[serde(rename = "dimension", skip_serializing_if = "Option::is_none")]
    pub dimension: Option<i32>,
    /// The number of vectors in the collection.
    #[serde(rename = "vector_count", skip_serializing_if = "Option::is_none")]
    pub vector_count: Option<i32>,
}

impl CollectionMeta {
    pub fn new() -> CollectionMeta {
        CollectionMeta {
            name: None,
            size: None,
            status: None,
            dimension: None,
            vector_count: None,
        }
    }
}


