/*
 * defaultTitle
 *
 * defaultDescription
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateRequestMetadataConfig : Configuration for the behavior of Pinecone's internal metadata index. By default, all metadata is indexed; when `metadata_config` is present, only specified metadata fields are indexed. To specify metadata fields to index, provide a JSON object of the following form:    ```   {\"indexed\": [\"example_metadata_field\"]}   ``` 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateRequestMetadataConfig {
    /// A list of metadata fields to index.
    #[serde(rename = "indexed", skip_serializing_if = "Option::is_none")]
    pub indexed: Option<Vec<String>>,
}

impl CreateRequestMetadataConfig {
    /// Configuration for the behavior of Pinecone's internal metadata index. By default, all metadata is indexed; when `metadata_config` is present, only specified metadata fields are indexed. To specify metadata fields to index, provide a JSON object of the following form:    ```   {\"indexed\": [\"example_metadata_field\"]}   ``` 
    pub fn new() -> CreateRequestMetadataConfig {
        CreateRequestMetadataConfig {
            indexed: None,
        }
    }
}


