/*
 * defaultTitle
 *
 * defaultDescription
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HnswConfig {
    #[serde(rename = "ef_construction", skip_serializing_if = "Option::is_none")]
    pub ef_construction: Option<i32>,
    #[serde(rename = "ef", skip_serializing_if = "Option::is_none")]
    pub ef: Option<i32>,
    #[serde(rename = "M", skip_serializing_if = "Option::is_none")]
    pub m: Option<i32>,
    #[serde(rename = "max_elements", skip_serializing_if = "Option::is_none")]
    pub max_elements: Option<i32>,
}

impl HnswConfig {
    pub fn new() -> HnswConfig {
        HnswConfig {
            ef_construction: None,
            ef: None,
            m: None,
            max_elements: None,
        }
    }
}


