/*
 * defaultTitle
 *
 * defaultDescription
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IndexMetaDatabaseMetadataConfig {
    #[serde(rename = "indexed", skip_serializing_if = "Option::is_none")]
    pub indexed: Option<Vec<String>>,
}

impl IndexMetaDatabaseMetadataConfig {
    pub fn new() -> IndexMetaDatabaseMetadataConfig {
        IndexMetaDatabaseMetadataConfig {
            indexed: None,
        }
    }
}


