/*
 * defaultTitle
 *
 * defaultDescription
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IndexMeta {
    #[serde(rename = "database", skip_serializing_if = "Option::is_none")]
    pub database: Option<Box<crate::models::IndexMetaDatabase>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::IndexMetaStatus>>,
}

impl IndexMeta {
    pub fn new() -> IndexMeta {
        IndexMeta {
            database: None,
            status: None,
        }
    }
}


