/*
 * defaultTitle
 *
 * defaultDescription
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchRequest {
    /// The desired number of replicas for the index.
    #[serde(rename = "replicas", skip_serializing_if = "Option::is_none")]
    pub replicas: Option<i32>,
    /// The new pod type for the index. One of `s1`, `p1`, or `p2` appended with `.` and one of `x1`, `x2`, `x4`, or `x8`.
    #[serde(rename = "pod_type", skip_serializing_if = "Option::is_none")]
    pub pod_type: Option<String>,
}

impl PatchRequest {
    pub fn new() -> PatchRequest {
        PatchRequest {
            replicas: None,
            pod_type: None,
        }
    }
}


